### ISSUE TITLE
Warnings with Todd-Coxeter Refactor

### ISSUE THREAD

**Issue by Joseph-Edwards** [libsemigroups/libsemigroups#489]
I am experiencing the same issues as described in #480, so tried compiling with Clang to see if my problems would go away. Regrettably, they didn't, and I came across the following warnings.

On a clean distribution, running
``` bash
./autogen.sh && ./configure CXX=clang++ && make 
```

yields the following warning:

``` cpp
In file included from src/presentation.cpp:31:
/home/joseph/Dev/Comp_Maths/libsemigroups/include/libsemigroups/presentation.hpp:1565:13: warning: ignoring return value of function declared with pure attribute [-Wunused-value]
            std::tolower(*it);
            ^~~~~~~~~~~~ ~~~
/home/joseph/Dev/Comp_Maths/libsemigroups/include/libsemigroups/presentation.hpp:1567:13: warning: ignoring return value of function declared with pure attribute [-Wunused-value]
            std::toupper(*it);
            ^~~~~~~~~~~~ ~~~
/home/joseph/Dev/Comp_Maths/libsemigroups/include/libsemigroups/presentation.hpp:1575:13: warning: ignoring return value of function declared with pure attribute [-Wunused-value]
            std::tolower(*it);
            ^~~~~~~~~~~~ ~~~
/home/joseph/Dev/Comp_Maths/libsemigroups/include/libsemigroups/presentation.hpp:1577:13: warning: ignoring return value of function declared with pure attribute [-Wunused-value]
            std::toupper(*it);
            ^~~~~~~~~~~~ ~~~

```
Config settings can be found [here](https://github.com/libsemigroups/libsemigroups/files/13204273/config.log).

**Comment by Joseph-Edwards** [comment]
The above warnings are now gone, but there are now new warnings:
```c++
/home/joseph/Dev/Comp_Maths/libsemigroups/extern/rx-ranges/include/rx/ranges.hpp:1676:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                               ^

/home/joseph/Dev/Comp_Maths/libsemigroups/extern/HPCombi/include/vect16.hpp:37:13: warning: definition of implicit copy constructor for 'Vect16' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vect16 &operator=(const Vect16 &) = default;
            ^

/home/joseph/Dev/Comp_Maths/libsemigroups/extern/HPCombi/include/perm16.hpp:49:62: note: in implicit copy constructor for 'HPCombi::Vect16' first required here
    HPCOMBI_CONSTEXPR_CONSTRUCTOR PTransf16(const vect vv) : Vect16(vv) {}
                                                             ^

src/todd-coxeter.cpp:118:61: warning: unused parameter 'stop_early' [-Wunused-parameter]
                                               bool         stop_early) {
                                                            ^

/home/joseph/Dev/Comp_Maths/libsemigroups/extern/HPCombi/include/vect_generic.hpp:50:18: warning: definition of implicit copy constructor for 'VectGeneric<16>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    VectGeneric &operator=(const VectGeneric &) = default;
                 ^
/home/joseph/Dev/Comp_Maths/libsemigroups/extern/HPCombi/include/vect_generic.hpp:207:16: note: in implicit copy constructor for 'HPCombi::VectGeneric<16>' first required here
        return res;
               ^
/home/joseph/Dev/Comp_Maths/libsemigroups/extern/HPCombi/include/epu_impl.hpp:394:41: note: in instantiation of member function 'HPCombi::VectGeneric<16>::eval' requested here
    return from_array(as_VectGeneric(v).eval().v);
                                        ^
```

Should I add the relevant warnings to an issue for HPCombi?

**Comment by james-d-mitchell** [comment]
I think we fixed the warning in HPCombi already, and I think I also fixed the other warning (I guess you are using clang to compile here). Can you try pulling again? Thanks @Joseph-Edwards

**Comment by Joseph-Edwards** [comment]
Yeah this seems to be working now (apart from the `stop_early` one). Not sure what the difference was, as I tried with `--disable-hpcombi` earlier and was still getting the `ranges` warnings. Must not have compiled it properly or something. Thanks for the fix.
